/**
 * Copyright 2017 California Institute of Technology ("Caltech").
 * U.S. Government sponsorship acknowledged.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gov.nasa.jpl.imce.oml.model.extensions;

public class OMLXcorePackages {
  public final /* XtextResourceSet */Object set;
  
  public final /* EPackage */Object c;
  
  public final /* EPackage */Object t;
  
  public final /* EPackage */Object g;
  
  public final /* EPackage */Object b;
  
  public final /* EPackage */Object d;
  
  public final /* EPackage */Object oml2oti;
  
  public OMLXcorePackages() {
    throw new Error("Unresolved compilation problems:"
      + "\nMap cannot be resolved to a type."
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field EcoreUtil is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nThe method or field EPackage is undefined"
      + "\nURI cannot be resolved to a type."
      + "\nURI cannot be resolved to a type."
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe method createXcoreResourceSet(Procedure1) from the type OMLXcorePackages refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.set refers to the missing type XtextResourceSet"
      + "\nThe field OMLXcorePackages.c refers to the missing type EPackage"
      + "\nThe field OMLXcorePackages.t refers to the missing type EPackage"
      + "\nThe field OMLXcorePackages.g refers to the missing type EPackage"
      + "\nThe field OMLXcorePackages.b refers to the missing type EPackage"
      + "\nThe field OMLXcorePackages.d refers to the missing type EPackage"
      + "\nThe field OMLXcorePackages.oml2oti refers to the missing type EPackage"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ncreatePlatformResourceURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\nresolveAll cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved"
      + "\ngetContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nget cannot be resolved");
  }
  
  public static /* XtextResourceSet */Object createXcoreResourceSet(final /* Procedure1<Map<URI, URI>> */Object standaloneURIMapInitializer) {
    throw new Error("Unresolved compilation problems:"
      + "\nMap cannot be resolved to a type."
      + "\nXtextResourceSet cannot be resolved."
      + "\nThe method or field EPackage is undefined"
      + "\n=== cannot be resolved."
      + "\nThe method or field EcorePlugin is undefined"
      + "\nThe method or field XcoreStandaloneSetup is undefined"
      + "\nThe method or field EcorePlugin is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field EcorePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field EcorePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XMLNamespacePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XMLNamespacePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XMLTypePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XMLTypePackage is undefined"
      + "\nThe method or field URI is undefined"
      + "\nThe method or field EcorePackage is undefined"
      + "\njava.lang.IllegalArgumentException cannot be resolved."
      + "\nThe method or field URI is undefined"
      + "\nThe method or field GenModelPackage is undefined"
      + "\njava.lang.IllegalArgumentException cannot be resolved."
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XtextPackage is undefined"
      + "\njava.lang.IllegalArgumentException cannot be resolved."
      + "\nThe method or field URI is undefined"
      + "\nThe method or field XcorePackage is undefined"
      + "\njava.lang.IllegalArgumentException cannot be resolved."
      + "\nThe method or field EcorePlugin is undefined"
      + "\nThe method or field XtextResource is undefined"
      + "\nThe method or field Boolean is undefined"
      + "\nURI cannot be resolved to a type."
      + "\nURI cannot be resolved to a type."
      + "\nsetPackageRegistry cannot be resolved"
      + "\nRegistry cannot be resolved"
      + "\nINSTANCE cannot be resolved"
      + "\ngetURIConverter cannot be resolved"
      + "\ngetURIMap cannot be resolved"
      + "\nworkspaceRoot cannot be resolved"
      + "\ndoSetup cannot be resolved"
      + "\nputAll cannot be resolved"
      + "\ncomputePlatformURIMap cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nput cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ntoURI cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\neNS_URI cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nempty cannot be resolved"
      + "\n! cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\neNS_URI cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nempty cannot be resolved"
      + "\n! cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\neNS_URI cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nempty cannot be resolved"
      + "\n! cannot be resolved"
      + "\ngetResource cannot be resolved"
      + "\ncreateURI cannot be resolved"
      + "\neNS_URI cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nempty cannot be resolved"
      + "\n! cannot be resolved"
      + "\napply cannot be resolved"
      + "\nputAll cannot be resolved"
      + "\ncomputePlatformURIMap cannot be resolved"
      + "\naddLoadOption cannot be resolved"
      + "\nOPTION_RESOLVE_ALL cannot be resolved"
      + "\nTRUE cannot be resolved");
  }
}
